#!/bin/sh
# Xcode Cloud runs this right after cloning the repo. The Xcode project is
# generated by XcodeGen (not committed), so generate it before the build.
set -e

if ! command -v xcodegen >/dev/null 2>&1; then
  brew install xcodegen
fi

cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

# The generated .xcodeproj is not committed, so its SwiftPM Package.resolved
# doesn't exist on a fresh CI clone. Xcode Cloud disables automatic dependency
# resolution and requires a resolved file, so resolve explicitly here (this
# writes Package.resolved into the freshly-generated project before the build).
xcodebuild -resolvePackageDependencies -project Fullball.xcodeproj -scheme Fullball
