#!/bin/sh
# Xcode Cloud runs this right after cloning the repo. The Xcode project is
# generated by XcodeGen (not committed), so generate it before the build.
set -e

if ! command -v xcodegen >/dev/null 2>&1; then
  brew install xcodegen
fi

cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

# Xcode Cloud disables automatic SwiftPM resolution and REQUIRES a committed
# Package.resolved (an explicit `xcodebuild -resolvePackageDependencies` also
# fails there with code 74). The generated .xcodeproj is gitignored, so its
# resolved file can't be committed in place. Instead we keep a tracked copy at
# ci_scripts/Package.resolved and drop it into the freshly-generated project.
# KEEP IN SYNC: after changing SPM deps/versions, regenerate locally and copy
# Fullball.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
# back to ci_scripts/Package.resolved.
RESOLVED_DIR="Fullball.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
mkdir -p "$RESOLVED_DIR"
cp ci_scripts/Package.resolved "$RESOLVED_DIR/Package.resolved"
